[default]
extend-ignore-words-re = ["(iterm.*|ITERM.*)", "[nN]oice.*"]
extend-ignore-re = [
  # ignore line with: # spellchecker:disable-line
  "(?Rm)^.*(#|//|--)\\s*spellchecker:disable-line$",
  # ignore block with # spellchecker:<on|off>
  "(?s)(#|//|--)\\s*spellchecker:off.*?\\n\\s*(#|//|--)\\s*spellchecker:on",
  # ignore bracketed mnemonics like [M]anager [I]nstall [d]efinition
  "\\[[A-Za-z]\\][a-z]+",
  # ignore vim leader keymaps like <leader>fo
  "<leader>[a-z]+",
  # ignore LESS_TERMCAP variables
  "LESS_TERMCAP_[a-z]+",
]

[files]
extend-exclude = [
  "Brewfile.lock.json",
  "iterm/xterm-256color-italic.terminfo",
  "iterm/xterm-256color-italic.ti",
  "config/vifm/vifm-help.txt",
  "config/vifm/devicons",
  "config/bat/themes/**",
  "CHANGELOG.md",
  "package-lock.json",
  "lazy-lock.json",
  "docs/**",
]
